name: Auto WordCloud Generator

on:
  schedule:
    - cron: '0 2 * * *'  # 每天10点（UTC+8）运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python generate_wordcloud.py

      - name: Upload artifact (optional backup)
        uses: actions/upload-artifact@v3
        with:
          name: wordcloud-output
          path: |
            movies.xlsx
            wordcloud.png
